### PR TITLE
150 readme + index

### PR DESCRIPTION
**Pull request by leonsuarez24**
Readme.md:

- [x] Improve the project description
- [x] Move "main.ipynb" to examples and rename it to demo_colab
- [x] Update the list of available features
- [x] Improve the Contributing section, include an explanation for "before_pr.sh", and rename it to quick_validation.sh

### CODE REVIEW

**Review by David-Morales-Norato — APPROVED** [review]
To me, this PR is Ok

**Review by bemc22 — CHANGES_REQUESTED** [review]
sorry but i can not find the explanation of "before_pr.sh" in the` contributing.rst` file, for the rest looks good for me.

**Comment by leonsuarez24** [comment]
> sorry but i can not find the explanation of "before_pr.sh" in the` contributing.rst` file, for the rest looks good for me.

Done, check again please

**Comment by bemc22** [comment]
LGTM

**Review by bemc22 — APPROVED** [review]

**Pull request merged**
